"""Pydantic request, response, health, and SSE wire models."""

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field, field_validator


class UserContext(BaseModel):
    # NestJS intentionally withholds the user's name from the AI service.
    fullName: str | None = None
    role: str
    kycStatus: str
    kycRejectionReason: str | None = None


class ChatRequest(BaseModel):
    """A single user question accepted by legal and support chat contracts."""

    message: str = Field(min_length=1, max_length=2000)
    # Generated by the browser once per submitted message. The same ID is
    # reused if the BFF retries the request, making the ticket tool idempotent.
    clientRequestId: UUID | None = None
    history: list[dict[str, str]] | None = None
    userContext: UserContext | None = None

    @field_validator("message")
    @classmethod
    def reject_blank_message(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("الرسالة مطلوبة")
        return value


class Source(BaseModel):
    """Public provenance for a legal passage or FAQ document used to ground an answer."""

    title: str
    article: str | None = None
    file: str
    source_url: str | None = None


class ChatResponse(BaseModel):
    """Completed non-streaming legal or support answer."""

    id: str
    content: str
    declined: bool
    sources: list[Source] = []


class TokenChunk(BaseModel):
    """One progressive text fragment in an SSE response."""

    type: Literal["token"] = "token"
    value: str


class DoneChunk(BaseModel):
    """Terminal SSE event identifying the answer, off-topic decision, and escalation status."""

    type: Literal["done"] = "done"
    id: str
    declined: bool = False
    escalated: bool = False
    suggestedGuide: list[str] = []


class HealthResponse(BaseModel):
    """Liveness/readiness state consumed by operators and containers."""

    status: Literal["ok", "degraded"]
    chroma: Literal["up", "down", "not_checked"]
    collection_count: int | None = None
